apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
spec:
  metrics:
  - name: cpu-usage-rate
    initialDelay: 10m
    successCondition: result[0] < 10
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1726-prometheus.prometheus.svc.cluster.local:9090
        query: |
          (sum(rate(container_cpu_usage_seconds_total{namespace="todo-application"}[10m])) / sum(machine_cpu_cores)) * 100