apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-scheduler
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-scheduler
            image: todo-scheduler
          restartPolicy: Never
