apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_USER: "postgres"
  POSTGRES_DATABASE: "postgres"
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      title VARCHAR(140) NOT NULL,
      done BOOLEAN NOT NULL DEFAULT false
    );
