apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-application
resources:
  - manifests/analysisTemplate.yaml
  - manifests/cronjob.yaml
  - manifests/databse-config.yaml
  - manifests/rollout.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/secret.yaml
  - manifests/statefulset.yaml
  - manifests/todo-app-service.yaml
  - manifests/todo-backend-service.yaml
images:
  - name: todo-app
    newName: lauriil12/devopswithkubernetes:todo-app4.02
  - name: todo-backend
    newName: lauriil12/devopswithkubernetes:todo-backend4.02
  - name: todo-scheduler
    newName: lauriil12/devopswithkubernetes:todo-scheduler2.09.5