apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config
      containers:
        - name: log-output-reader
          image: log-output-reader
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: PINGPONGPORT
              value: "2345"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
        - name: log-output-writer
          image: log-output-writer
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
