apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: todo-volume
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todo-app
          image: lauriil12/devopswithkubernetes:todo-app2.02
          volumeMounts:
            - name: todo-volume
              mountPath: /usr/src/app/images
          env:
            - name: PORT
              value: "3000"
            - name: IMAGEURL
              value: "https://picsum.photos/1200"
            - name: POLLINTERVAL
              value: "3600000"
        - name: todo-backend
          image: lauriil12/devopswithkubernetes:todo-backend2.02
          env:
            - name: PORT
              value: "3001"
