apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - manifests/databse-config.yaml
  - manifests/deployment.yaml
  - manifests/secret.enc.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
images:
  - name: ping-pong
    newName: lauriil12/devopswithkubernetes:ping-pong4.01