apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
  # - manifests/secret.yaml # This is created locally for Argo cd
resources:
- manifests/databse-config.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
images:
- name: ping-pong
  newName: lauriil12/devopswithkubernetes
  newTag: ping-pong-8049a763df117e40bd777e05d18c1e20b33872e5
