apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - manifests/databse-config.yaml
  - manifests/deployment.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
