name: Build and publish application

on:
  push:
    paths:
      - '4/ping-pong/**'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: local

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish ping-pong
        run: |-
          docker build -f ./4/ping-pong/Dockerfile --tag "lauriil12/devopswithkubernetes:ping-pong-$GITHUB_SHA" ./4/ping-pong/
          docker push "lauriil12/devopswithkubernetes:ping-pong$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image
        run: kustomize edit set image ping-pong=lauriil12/devopswithkubernetes:ping-pong-$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: '4/ping-pong/kustomization.yaml'
          message: New version released ${{ github.sha }}